### ISSUE TITLE
Multiple Wordpress Deployments

### ISSUE THREAD

**Issue by kamilikamil** [stcox/charts#11]
Can I deploy multiple WordPress websites using this method or I would have to repeat all the steps for each new WordPress deployment?

**Comment by stcox** [comment]
Yes, after [initializing the cluster for site deployments](https://github.com/stcox/gke-wordpress/blob/master/USAGE.md#installation), you could deploy multiple sites with a short script that runs a `helm install` command for each site. Before you run the script though, you should make sure each site is configured and ready to be deployed as described in [Adding Sites](https://github.com/stcox/gke-wordpress/blob/master/USAGE.md#adding-sites), including ensuring:
1. each site has a values.yaml file based on the default [wordpress/values.yaml](https://github.com/stcox/gke-wordpress/blob/master/wordpress/values.yaml) file, with custom values you supply (e.g., namespace, domain name, memory + storage reqs, etc.),
2. each site's domain name A record points to the Nginx Load Balancer IP,
3. each site requires a Persistent Disk (PD). Although GKE WordPress is configured to automatically provision PDs using Dynamic Storage Provisioning, some clusters currently require Manual Storage Provisioning. If Dynamic Storage Provisioning doesn't work on your cluster, create a Persistent Disk for each site manually with the command described in [Adding Sites - Step 3](https://github.com/stcox/gke-wordpress/blob/master/USAGE.md#adding-sites).
