### ISSUE TITLE
Ngnix-Ingress resources

### ISSUE THREAD

**Issue by cloudgrimm** [stcox/charts#12]
Great documentation and tutorial, I wanted to ask on the nginx ingress resources

Since its in a different namespace as that of wordpress sites, how does it recognise it as a controller?

**Comment by stcox** [comment]
Let me know if [this](https://kubernetes.github.io/ingress-nginx/how-it-works/#how-it-works) helps, or [this](https://kubernetes.io/docs/concepts/services-networking/ingress/).
