### ISSUE TITLE
Autoscaling with Persistence disks

### ISSUE THREAD

**Issue by cloudgrimm** [stcox/charts#13]
I have only one site to deploy so i just did a wordpress deployment directly using the documentation provided without creating a separate folder for a given site.

When I try to add 2 replicas I get a multi attach volume error. How can I easily autoscale the wordpress deployment horizontally with using persistence disks on gcp?

**Comment by stcox** [comment]
Try a [regional cluster](https://cloud.google.com/kubernetes-engine/docs/how-to/creating-a-cluster#regional) with a [regional PD](https://cloud.google.com/solutions/using-kubernetes-engine-to-deploy-apps-with-regional-persistent-disks). Keep me posted.
