### ISSUE TITLE
gke-drupal implementation

### ISSUE THREAD

**Issue by cloudgrimm** [stcox/charts#14]
Wanted to ask if this approach can be used for a drupal implementation, 

It would be great to have such an implementation? If anyone has managed to do it a guide would be helpful.

**Comment by stcox** [comment]
This Kubernetes/Helm approach should work with Drupal. Fork the [gke-wordpress](https://github.com/stcox/gke-wordpress), [wordpress](https://github.com/stcox/wordpress) and [nginx](https://github.com/stcox/nginx) projects. Use wordpress and nginx images as templates to make your own custom php/nginx images for Drupal. In `gke-wordpress`, replace `wordpress` with `drupal` and edit files to reflect your custom Drupal installation configuration.
