### ISSUE TITLE
Bedrock?

### ISSUE THREAD

**Issue by alicam** [stcox/charts#2]
Steve,

I'll likely have a few questions, which are not issues, as such. Let me know if you'd rather I ask elsewhere.

Now, I'm new to K8S and trying hard(!).

My much preferred approach to WordPress is dep management via Composer using Bedrock. 

There are a few dockerized Bedrock implementations out there, but it's beyond my current skills to take your code and swap out your WordPress image for a Bedrock one, and to also make sure the other bits required for Bedrock are there (Composer, and then Yarn/NPM/Gulp etc for building the theme).

Is that hard to do? Is it something you could offer any help with?

Many thanks

A

**Comment by stcox** [comment]
Feel free to fork this project to create a Bedrock version. Sorry, I can't help with it right now.
