### ISSUE TITLE
Can't run it!

### ISSUE THREAD

**Issue by alicam** [stcox/charts#3]
I have this error:

$ helm install -f ./wp-sites/day3-io.yaml ./gke-wordpress/wordpress
Error: apiVersion "apps/v1" in wordpress/templates/wordpress-deployment.yaml is not available

This apiVersion ("apps/v1") is listed in three files, and each causes an issue for WP, Redis and Kube-LEGO.

So I don't know how to fix that.

As best I can tell I'm running latest versions of everything, if that helps...?

A

**Comment by stcox** [comment]
For apps/v1 support: When creating your cluster, be sure to specify a Cluster Version greater than or equal to 1.9 for apps/v1 support.

To check your current Cluster Version, run 'kubectl version' and look at "Server Version: Git Version" results

See: https://kubernetes.io/blog/2017/12/kubernetes-19-workloads-expanded-ecosystem/ and https://github.com/kubernetes/kubernetes/issues/61430.

I've added this requirement to the usage.md prerequisites.

Thank you.
