### ISSUE TITLE
Attempting to deploy a site gives an error that the disk is not found.

### ISSUE THREAD

**Issue by EvilChookie** [stcox/charts#4]
When I run the command:

```
helm install -f ./wp-sites/mysite-com.yaml ./gke-wordpress/wordpress
```

I get the following message:

```
Error: release exhaling-stingray failed: persistentvolumes "wp-mysite-com-pv" is forbidden: error querying GCE PD volume mysite: disk is not found
```

I _was_ able to start the nginx, redis and lego containers successfully - it's only the wordpress ones that are causing a problem. My first thought was that I was using a restricted service account for my cluster - so I tried creating a fresh one with the Google suggested account and permissions (i.e, the default command they give you in the tutorial) and that didn't resolve the problem either. I've also tried a fresh cluster that has "Full Control" to the Cloud API, as well as a fresh cluster that has an explicit "Read Write" under storage (although I'm not sure if that actually makes a difference here)

Looking at the logs for "GKE Cluster Operations" I can see that it's started and pulled Redis - but there's no error that concerns my storage for my failed container.

I can see that the container itself is created - running `helm list` shows a `wordpress-0.1.0` instance that is failed (and attempting to deploy again will fail, as it's already in use). I need to remove it again before I can redeploy.

In researching this error, I've seen a lot of this error popping up in reports for Kubernetes itself on GCE, which seem to be fixed in my version (which is running `1.9.7-gke.6`).

I'm pretty fresh with GCE and k8s, and just putting around to see what it can do for me - so any thoughts you've got on what I've done wrong would be awesome :) It'd be great to also know _exactly_ what permissions are required to run everything - so I can create a service account for the cluster in production which has only the exact required permissions.

Let me know if I can provide any further information :)

**Comment by mshick** [comment]
Same error here. Latest kubectl (1.11.3) and helm (2.10.0).

**Comment by stcox** [comment]
thanks for your input, i will take a look at it and let you know

**Comment by stcox** [comment]
@evilchookie - After installing redis, did you run `kubectl create -f ./gke-wordpress/storageclass.yaml`? I'm currently running a gke-wordpress cluster successfully with `1.9.6-gke.2`, but I haven't checked any later versions.

**Comment by mshick** [comment]
I ran that, yes. It gave positive results.

**Comment by stcox** [comment]
Thanks, @mshick. I'll keep working on it. It may take some time.

**Comment by karban01** [comment]
@stcox I am having an issue with this also but did some changing around to make it work. I had to explicitly specify the PD that I manually created so it could create the pv and pvc.

**Comment by stcox** [comment]
I've added a step 3 to the USAGE instructions to manually add persistent volumes, until I figure out why dynamic provisioning isn't working. Running `gcloud compute disks create --size=<disk-size> --zone=<cluster-zone> mysite-com` creates a new persistent volume. See [Usage.MD](https://github.com/stcox/gke-wordpress/blob/master/USAGE.md), Adding Sites, step 3, for an example.
