### ISSUE TITLE
nginx ingress issue

### ISSUE THREAD

**Issue by karban01** [stcox/charts#5]
I deployed this helm chart based off the documentation that was supplied and made the changes as requested but the ingress does not seem to be connecting to anything. I thought there as something wrong with my deployment but I selected the WP deployment and did a manual expose command and created a GCP loadbalancer/ingress and it works. The site loaded and everything. So some reason the ingress that is deploying is not working as intended.

**Comment by stcox** [comment]
During installation, and after you install the LoadBalancer, described in Usage - Installation - Step 3, `helm install nginx-ingress`,

Run:

 `watch kubectl describe svc nginx --namespace nginx-ingress`

It'll take a few minutes for the LoadBalancer to be ready. Once it's ready, the above service description command should supply information about the LoadBalancer that may be helpful in debugging this issue.
