### ISSUE TITLE
Redis connection issue

### ISSUE THREAD

**Issue by karban01** [stcox/charts#6]
We installed the correct Redis Object Cache plugin but wont connect to the redis instanced based off the values given.

here is the diagnostic log

<b>Warning</b>:  Redis::connect(): connect() failed: Connection refused in <b>/var/www/html/wp-content/object-cache.php</b> on line <b>436</b><br />
Status: Not Connected
Client: PhpRedis (v3.1.4)
Drop-in: Valid
Connection Exception: Redis server went away (RedisException)
Redis Extension: 3.1.4
Predis Client: 1.1.1
PHP Version: 7.2.4
Multisite: No
Global Prefix: "wp_"
Blog Prefix: "wp_"

**Comment by stcox** [comment]
Try this info in wp-config.php:
```
define('WP_CACHE_KEY_SALT', 'mysite-com');
define('WP_REDIS_CLIENT', 'pecl');
define('WP_REDIS_SCHEME', 'tcp');
define('WP_REDIS_HOST', 'redis.redis');
define('WP_REDIS_PORT', '6379');
```
