### ISSUE TITLE
Error mysql version 8 with WP

### ISSUE THREAD

**Issue by josselinlbe** [stcox/charts#8]
Hi stcox,

**Error:** 
`
Warning: mysqli::__construct(): Error while reading greeting packet. PID=125 in Standard input code on line 22 
Warning: mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
MySQL Connection Error: (2006) MySQL server has gone away
`

**Ideas:**
Wordpress latest does not works with mysql latest container [ref ](https://github.com/docker-library/wordpress/issues/313)
Changes in MySQL 8.0 [ref](https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password-compatible-connectors)

On my Google Cloud SQL:
`MySQL [(none)]> ALTER USER proxyuser
    ->   IDENTIFIED WITH caching_sha2_password
    ->   BY 'password';
ERROR 1524 (HY000): Plugin 'caching_sha2_password' is not loaded`

Do you have any ideas to resolve this issue ?

**Comment by ertw0405** [comment]
I am experiencing the same issue and im fairly new to this whole env so need help as well

**Comment by ertw0405** [comment]
found issue saying "cannot connect to database" from stackdriver

**Comment by ertw0405** [comment]
could it be the problem with the cloudsql-proxy setup?

**Comment by josselinlbe** [comment]
@ertw0405 Did you configure it correctly `dbCred: '{}'` ? 
I don't think it's cloudsql-proxy setup, it's probably a problem with Wordpress & Mysql 8.0

**Comment by josselinlbe** [comment]
Problem solved. This was the dbCred variable.

**Comment by stcox** [comment]
@seelixe, sorry I wasn't able to respond sooner. @ertw0405, please ensure the `dbConn` and `dbCred` fields in `mysite-com.yaml` file are populated. Open a new issue if your still having trouble.
